CREATE TABLE stable_horses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    showname TEXT,
    age INTEGER NOT NULL,
    breed TEXT,
    riderId INTEGER REFERENCES stable_riders(id)
);